import { randomBytes } from "node:crypto";
import { resolve } from "node:path";
import {
  DurableBatchStore,
  loadOrCreateBatchEncryptionKey,
  runBatchWindow,
  type BatchChildRecord,
  type BatchExecutionResult,
  type BatchMode,
  type BatchRecord,
  type BatchState,
  type CreateBatchChildInput,
} from "@morrow/batch-engine";
import {
  isJsonObject,
  sha256Json,
  sha256Text,
  type CatalogTool,
  type JsonObject,
} from "@morrow/contracts";
import type { GatewayConfig } from "./config.js";
import { GatewayRuntime } from "./runtime.js";

export const MORROW_BATCH_TOOL_NAMES = Object.freeze([
  "morrow_batch_health",
  "morrow_batch_create",
  "morrow_batch_get",
  "morrow_batches_recent",
  "morrow_batch_run",
  "morrow_batch_pause",
  "morrow_batch_cancel",
] as const);

export interface CreateGatewayBatchOperationInput {
  readonly childId?: string;
  readonly tool: string;
  readonly arguments: JsonObject;
  readonly sourceBindingId?: string;
}

export interface CreateGatewayBatchInput {
  readonly name: string;
  readonly mode: BatchMode;
  readonly concurrency: number;
  readonly operations: readonly CreateGatewayBatchOperationInput[];
}

export interface GatewayBatchPageInput {
  readonly batchId: string;
  readonly offset?: number;
  readonly limit?: number;
}

export interface RecentBatchesInput {
  readonly state?: BatchState;
  readonly limit?: number;
}

export interface RunGatewayBatchInput {
  readonly batchId: string;
  readonly maxChildren?: number;
}

function publicTool(runtime: GatewayRuntime, name: string): CatalogTool {
  const normalized = String(name || "").trim();
  const tool = runtime.catalog.tools.find((candidate) => candidate.publicName === normalized);
  if (!tool) throw new Error(`Unknown Morrow tool ${normalized}.`);
  return tool;
}

function normalizeBatchArguments(
  mapping: CatalogTool,
  rawArguments: JsonObject,
  sourceBindingId?: string,
): JsonObject {
  const args = structuredClone(rawArguments);
  if (mapping.upstreamId !== "morrow-legacy") {
    if (args._morrow !== undefined || sourceBindingId) {
      throw new Error("_morrow routing controls apply only to Morrow legacy tools");
    }
    return args;
  }

  const existing = isJsonObject(args._morrow) ? args._morrow : {};
  if (existing.operation_id !== undefined) {
    throw new Error("Batch operation identity is generated by Morrow and cannot be supplied in child arguments");
  }
  const embeddedBinding = typeof existing.source_binding_id === "string"
    ? existing.source_binding_id.trim()
    : "";
  const requestedBinding = String(sourceBindingId || "").trim();
  if (embeddedBinding && requestedBinding && embeddedBinding !== requestedBinding) {
    throw new Error("The child contains two different source binding ids");
  }
  const selectedBinding = requestedBinding || embeddedBinding;
  args._morrow = {
    ...(selectedBinding ? { source_binding_id: selectedBinding } : {}),
  };
  return args;
}

function gatewayMeta(value: JsonObject): Record<string, unknown> | null {
  if (!isJsonObject(value._meta)) return null;
  const meta = value._meta["io.morrow/gateway"];
  return isJsonObject(meta) ? meta : null;
}

function problemCode(value: JsonObject): string {
  if (!isJsonObject(value.structuredContent)) return "";
  return typeof value.structuredContent.code === "string"
    ? value.structuredContent.code.trim()
    : "";
}

function childResult(
  runtime: GatewayRuntime,
  batch: BatchRecord,
  child: BatchChildRecord,
  result: JsonObject,
): BatchExecutionResult {
  const meta = gatewayMeta(result);
  const operationId = typeof meta?.gatewayOperationId === "string"
    ? meta.gatewayOperationId
    : "";
  const operation = operationId
    ? runtime.operationGet(operationId)
    : null;
  const gatewayOperationState = isJsonObject(operation) && typeof operation.state === "string"
    ? operation.state
    : typeof meta?.gatewayOperationState === "string"
      ? meta.gatewayOperationState
      : "";
  const sourceResultState = isJsonObject(operation) && typeof operation.sourceResultState === "string"
    ? operation.sourceResultState
    : "";
  const sourceTaskId = isJsonObject(operation) && typeof operation.sourceTaskId === "string"
    ? operation.sourceTaskId
    : "";
  const resultDigest = sha256Json(result);

  if (gatewayOperationState === "source_unknown") {
    return {
      state: "unknown",
      resultDigest,
      ...(operationId ? { gatewayOperationId: operationId } : {}),
      gatewayOperationState,
      ...(sourceResultState ? { sourceResultState } : {}),
      ...(sourceTaskId ? { sourceTaskId } : {}),
      errorDigest: sha256Text("gateway_source_unknown"),
    };
  }

  if (result.isError === true) {
    return {
      state: problemCode(result) === "operation_already_recorded"
        && gatewayOperationState === "response_received"
        ? "succeeded"
        : "failed",
      resultDigest,
      ...(operationId ? { gatewayOperationId: operationId } : {}),
      ...(gatewayOperationState ? { gatewayOperationState } : {}),
      ...(sourceResultState ? { sourceResultState } : {}),
      ...(sourceTaskId ? { sourceTaskId } : {}),
      errorDigest: sha256Text(problemCode(result) || "gateway_tool_error"),
    };
  }

  if (batch.mode === "stage_writes" && !sourceTaskId) {
    return {
      state: "unknown",
      resultDigest,
      ...(operationId ? { gatewayOperationId: operationId } : {}),
      ...(gatewayOperationState ? { gatewayOperationState } : {}),
      ...(sourceResultState ? { sourceResultState } : {}),
      errorDigest: sha256Text("staged_write_missing_source_task"),
    };
  }

  return {
    state: "succeeded",
    resultDigest,
    ...(operationId ? { gatewayOperationId: operationId } : {}),
    ...(gatewayOperationState ? { gatewayOperationState } : {}),
    ...(sourceResultState ? { sourceResultState } : {}),
    ...(sourceTaskId ? { sourceTaskId } : {}),
  };
}

function statePath(config: GatewayConfig, override?: string): string {
  return override || config.operationJournal.path;
}

export class MorrowRuntime {
  readonly gateway: GatewayRuntime;
  readonly batches: DurableBatchStore;

  private constructor(gateway: GatewayRuntime, batches: DurableBatchStore) {
    this.gateway = gateway;
    this.batches = batches;
  }

  static async connect(
    config: GatewayConfig,
    options: { readonly statePath?: string; readonly batchKeyPath?: string } = {},
  ): Promise<MorrowRuntime> {
    const reserved = new Set([
      ...config.filters.excludeNames,
      ...MORROW_BATCH_TOOL_NAMES,
    ]);
    const effectiveConfig: GatewayConfig = {
      ...config,
      filters: {
        ...config.filters,
        excludeNames: [...reserved].sort(),
      },
    };
    const path = statePath(effectiveConfig, options.statePath);
    const gateway = await GatewayRuntime.connect(effectiveConfig, { journalPath: path });
    try {
      const key = path === ":memory:"
        ? randomBytes(32)
        : loadOrCreateBatchEncryptionKey(
          resolve(options.batchKeyPath || `${path}.batch.key`),
        );
      const batches = new DurableBatchStore({ path, encryptionKey: key });
      return new MorrowRuntime(gateway, batches);
    } catch (error) {
      await gateway.close();
      throw error;
    }
  }

  batchHealth(): JsonObject {
    const recent = this.batches.list(200);
    return {
      schema: "morrow.batch-store.health.v1",
      path: this.batches.path,
      recentBatchCount: recent.length,
      recentCoverageComplete: recent.length < 200,
      activeBatches: recent.filter((batch) => ["planned", "running", "paused"].includes(batch.state)).length,
      inspectionRequiredBatches: recent.filter((batch) => batch.state === "inspection_required").length,
    };
  }

  batchCreate(input: CreateGatewayBatchInput): JsonObject {
    if (!Array.isArray(input.operations) || input.operations.length === 0) {
      throw new Error("A batch requires at least one explicit operation");
    }
    const children: CreateBatchChildInput[] = input.operations.map((operation) => {
      const mapping = publicTool(this.gateway, operation.tool);
      const readOnly = mapping.annotations?.readOnlyHint === true;
      if (input.mode === "read_only" && !readOnly) {
        throw new Error(`read_only batch cannot include ${mapping.publicName}`);
      }
      if (input.mode === "stage_writes" && (readOnly || mapping.upstreamId !== "morrow-legacy")) {
        throw new Error(
          `stage_writes batch currently accepts only Morrow legacy write tools; ${mapping.publicName} is not eligible`,
        );
      }
      return {
        ...(operation.childId ? { childId: operation.childId } : {}),
        publicToolName: mapping.publicName,
        sourceId: mapping.upstreamId,
        sourceToolName: mapping.upstreamName,
        readOnly,
        arguments: normalizeBatchArguments(mapping, operation.arguments, operation.sourceBindingId),
      };
    });
    const concurrency = input.mode === "stage_writes"
      ? Math.min(input.concurrency, 4)
      : input.concurrency;
    const detail = this.batches.create({
      name: input.name,
      mode: input.mode,
      catalogDigest: this.gateway.catalog.digest,
      concurrency,
      children,
    });
    return {
      schema: "morrow.batch-created.v1",
      batch: detail.batch,
      returnedChildren: Math.min(detail.children.length, 25),
      children: detail.children.slice(0, 25),
      note: input.mode === "stage_writes"
        ? "Running this batch stages donor tasks only. Each task still requires separate human approval in Morrow."
        : "Running this batch performs bounded read-only operations.",
    };
  }

  batchGet(input: GatewayBatchPageInput): JsonObject {
    const page = this.batches.listChildren(
      input.batchId,
      input.offset ?? 0,
      input.limit ?? 100,
    );
    return {
      schema: "morrow.batch-detail.v1",
      batch: page.batch,
      offset: page.offset,
      returned: page.returned,
      nextOffset: page.nextOffset,
      children: page.children,
    };
  }

  batchesRecent(input: RecentBatchesInput = {}): JsonObject {
    const requestedLimit = Math.max(1, Math.min(input.limit ?? 50, 200));
    const candidates = this.batches.list(input.state ? 200 : requestedLimit);
    const batches = (input.state
      ? candidates.filter((batch) => batch.state === input.state)
      : candidates
    ).slice(0, requestedLimit);
    return {
      schema: "morrow.batches.list.v1",
      returned: batches.length,
      batches,
    };
  }

  async batchRun(input: RunGatewayBatchInput): Promise<JsonObject> {
    const result = await runBatchWindow(
      this.batches,
      input.batchId,
      async ({ batch, child, arguments: args }) => {
        const forwarded = structuredClone(args) as Record<string, unknown>;
        if (child.sourceId === "morrow-legacy" && child.sourceOperationId) {
          forwarded._morrow = {
            ...(isJsonObject(forwarded._morrow) ? forwarded._morrow : {}),
            operation_id: child.sourceOperationId,
          };
        }
        const resultValue = await this.gateway.call(child.publicToolName, forwarded);
        return childResult(this.gateway, batch, child, resultValue);
      },
      {
        expectedCatalogDigest: this.gateway.catalog.digest,
        maxChildren: input.maxChildren,
      },
    );
    return result as unknown as JsonObject;
  }

  batchPause(batchId: string): JsonObject {
    return this.batches.pause(batchId) as unknown as JsonObject;
  }

  batchCancel(batchId: string): JsonObject {
    return this.batches.cancel(batchId) as unknown as JsonObject;
  }

  async close(): Promise<void> {
    this.batches.close();
    await this.gateway.close();
  }
}
